### ISSUE TITLE
Future zuul project

### ISSUE THREAD

**Issue by romariolodder** [Confluex/Zuul#83]
I found out that the devnull.org website is offline. Is this project still supported? How does the roadmap looks like?

**Comment by psmith** [comment]
I'm currently rebranding/converting zuul over to be supported by Confluex.  Mike (devnull.org) used to work here, and doesn't have time to support zuul anymore.

Roadmap
1) Finish all the rebranding and converting. I'm almost done. I haven't even started getting some to the content from devnull.org over, or replicate it yet.
2) There has been new work done. There is a new spring client, that behaves differently. It's the 1.6 branch, if you would like to take a look.  Adds some features, and changes some things quite a bit.  Also, there is a 1.6 version of Zuul, that I'm not pushing to master for a few reasons. Mainly, it fixes some of the issues with how encryption appears to behave, but adds a new problem.  It's more obvious what it's doing with encryption, but next to impossible to actually show a good error message.  I'd like more feedback.  Mike and I worked on that feature/code quite a while ago.

After rebranding, etc is completed (it's a whole lot of little things I keep missing).

I'll knock out a few of the simple things, like always using https for gravatar images (currently uses http).  Also, upgrade the spring version and other libraries in the project to more current versions. This should help with Java 8 and Tomcat 8 support.

Next, figure out where to go with authentication since openid 2.0 is pretty much dead. Looking at openid connect, and just oauth 2.

Finally, come up with a better way to display and deal with encryption on the admin site.  I'd like it to behave more like a password safe.  Where it's obvious if something is encrypted. Also, where you can "decrypt/show" an encrypted value without going back to the db.  This isn't a trivial problem to fix. 1.6 version fixes part of the display issue, but causes some new ones.

After that, I have a whole lot of ideas, as do many others on improvements.
